# Generated by Django 4.1 on 2023-05-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': '站点表', 'verbose_name_plural': '站点表'},
        ),
        migrations.AlterField(
            model_name='asin',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.shop', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='asin',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='asin',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.staff', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.post', verbose_name='岗位'),
        ),
    ]
